/* ============================================================
   THE REAL FLOCK — 33 birds currently listed on
   feathered-friends.com (scraped 2026-07-09).
   Bios are the sanctuary's own words. Photos in /public/birds/.
   ============================================================ */

export const BIRDS = [
  {
    "slug": "bubba",
    "name": "Bubba",
    "group": "Amazon",
    "photo": "/birds/bubba.jpg",
    "species": "Yellow-Crowned Amazon",
    "age": "~7 years",
    "sex": "Male",
    "facts": "Amazon",
    "noise": 4,
    "exp": "Some experience",
    "bio": "Meet Bubba.\n\nBubba is an approximately 7 year old male Yellow Crown Amazon.\n\nBubba is a funny bird, and he'll melt your heart with his goofy antics, but he's an Amazon, and Amazons take some time to warm up to humans. So when meeting Bubba, be patient and open to forming a bond on his terms. Once he decides you're a safe human, you'll see a bird that's capable of being your long-time best friend!\n\nHe's a young Amazon, so please keep that in mind when considering adoption."
  },
  {
    "slug": "babi",
    "name": "Babi",
    "group": "Amazon",
    "photo": "/birds/babi.jpg",
    "species": "Blue-Fronted Amazon",
    "age": "27 years",
    "sex": "Male",
    "facts": "Amazon",
    "noise": 5,
    "exp": "Some experience",
    "bio": "Meet Babi.\n\nBabi is a 27-year-old male Blue Front Amazon.\n\nBabi wants to meet you. Babi wants to meet EVERYONE. Babi wants to hang out, have LONG conversations, and spend every second in your adoring attention.\n\nBabi is one of the funniest Amazons you'll ever meet, but be warned, he is LOUD. And if you aren't giving him attention, he has no problem letting you know that is unacceptable.\n\nBabi will make a fantastic companion for someone who has a LOT of time to spend with him. If you've got all day to whistle, hum and sing, Babi is the guy for you!"
  },
  {
    "slug": "elsa-olaf",
    "name": "Elsa & Olaf",
    "group": "Cockatiel",
    "photo": "/birds/elsa-olaf.jpg",
    "species": "Lutino & White-faced Pied Cockatiels",
    "age": "~4 years",
    "sex": "Bonded pair",
    "facts": "Cockatiel",
    "noise": 2,
    "exp": "Beginner-friendly",
    "bonded": true,
    "bio": "Meet Elsa & Olaf.\n\nElsa is an approximately 4 year old Lutina Cockatiel, and Olaf is an approximately 4 year old White-face Pied Cockatiel.\n\nElsa & Olaf are working hard to become fans of being handled. They definitely show potential, and with the right human working with them, they could blossom into amazing companions.\n\nWhile they are learning to love human contact, they are also content to sing and dance with you from the safety of their cage.  They don't show aggression. They mostly just avoid anything they don't care for.\n\nThese two are going to be amazing feathered friends in the right home!"
  },
  {
    "slug": "puddin",
    "name": "Puddin'",
    "group": "Cockatoo",
    "photo": "/birds/puddin.jpg",
    "species": "Goffin's Cockatoo",
    "age": "20+ years",
    "sex": "Male (assumed)",
    "facts": "Cockatoo",
    "noise": 4,
    "exp": "Experienced homes only",
    "special": "Mostly blind — narrates life beautifully anyway",
    "bio": "Hi. I'm Puddin.\n\nI am a Goffin's Cockatoo.\n\nThe humans don't know how old I am, but they assume I'm male and at least 20 years old.\n\nI come from a rough background. I've only known the hard life. I've got some trust issues.\n\nI'm mostly blind so every day life is a little harder for me than the other guys, but I get by! I'm resilient.\n\nI'm looking for a human who is willing to take it slow. I want a long-term relationship, but those trust issues require us not to rush into anything too quickly.\n\nI find it very helpful in the trust building phase of the relationship for the human to talk me through everything - tell me where you are, what you're doing, who you're with.... I know what that SOUNDS like, but no, no, no... I mean, when you're trying to have some one on one time with me, make sure I know everything that's happening so I'm not startled by something. I hate surprises!\n\nI really want to meet you and become your BFF, but please be patient with me. I likely won't be able to fulfill your love at first sight fantasies, but, again, I'm blind! 🤪"
  },
  {
    "slug": "houdini",
    "name": "Houdini",
    "group": "Cockatoo",
    "photo": "/birds/houdini.jpg",
    "species": "Yellow-Crested Cockatoo",
    "age": "Unknown",
    "sex": "Male (assumed)",
    "facts": "Cockatoo",
    "noise": 3,
    "exp": "Experienced homes only",
    "bio": "Meet Houdini.\n\nHoudini is an unknown aged assumed male Yellow Crested Cockatoo.\n\nHoudini is new to just being a cockatoo and not a breeder bird, so he's pretty quiet and shy in the Sanctuary.\n\nHoudini is quite unsure of humans, so he's going to take some time to warm up to someone. We have no doubt that once Houdini chooses a human to trust, he will be an amazing companion!"
  },
  {
    "slug": "big-boy",
    "name": "Big Boy",
    "group": "Cockatoo",
    "photo": "/birds/big-boy.jpg",
    "species": "Umbrella Cockatoo",
    "age": "Unknown",
    "sex": "Male (assumed)",
    "facts": "Cockatoo",
    "noise": 5,
    "exp": "Experienced homes only",
    "bio": "Meet Big Boy.\n\nBig Boy is an unknown aged assumed male Umbrella Cockatoo.\n\nBig Boy is really just learning how to be a cockatoo. His previous life didn't offer much chance for being a \"normal\" cockatoo in captivity, so he doesn't really know what to do with himself yet.\n\nBig Boy is learning how to play, dance, destroy paper, and scream with the best of them, in true cockatoo fashion!\n\nHe has not shown any aggression towards anyone, but he is VERY unsure of humans right now. He WILL let you give him some scritches from the safety of his cage at this time.\n\nBig Boy needs a human he can learn to trust, and once that happens, Big Boy is very likely to be an amazing companion!"
  },
  {
    "slug": "star",
    "name": "Star",
    "group": "Cockatoo",
    "photo": "/birds/star.jpg",
    "species": "Bare-Eyed Cockatoo",
    "age": "20+ years",
    "sex": "Male (assumed)",
    "facts": "Cockatoo",
    "noise": 5,
    "exp": "Experienced homes only",
    "bio": "Meet Star.\n\nStar is a 20+ year old assumed male Bare Eyed Cockatoo.\n\nStar has some SERIOUS personality! He is funny, goofy, charming and loveable.\n\nUnfortunately,  Star also has some major cage aggression right now, but our volunteers have been working with him to help him overcome that.\n\nStar will need a human with patience, consistency, and the ability to handle the screams of a cockatoo. Someone who can read  parrot body language and the ability to work on training are super important with Star."
  },
  {
    "slug": "sweetie-booboo",
    "name": "Sweetie & BooBoo",
    "group": "Cockatoo",
    "photo": "/birds/sweetie-booboo.jpg",
    "species": "Umbrella Cockatoos",
    "age": "Unknown",
    "sex": "Bonded pair (F & M)",
    "facts": "Cockatoo",
    "noise": 5,
    "exp": "Experienced homes only",
    "bonded": true,
    "bio": "Meet Sweetie & BooBoo.\n\nSweetie & Boo are unknown aged Female and Male Umbrella Cockatoos.\n\nThey will need to be adopted to a home together as they are bonded.\n\nThis pair has been with us since August 4, 2012.\n\nThey are not fond of being handled, and get nervous when arms, perches, or towels are brought near or inside of their cage. They do like to come out of their cage on their own terms and will walk around.\n\nThese two, though nervous, are very sweet. Sweetie tends to seek attention more than BooBoo, who is very skittish and flighty. The two enjoy their fresh fruit and vegetables, and especially love nutriberries!\n\nBooBoo seems nervous when receiving spray baths, but Sweetie enjoys hers.\n\nThey are loud and can be just as unpredictable as any other cockatoo. They would do best with an owner who has cockatoo experience and knows how to handle large, unpredictable birds."
  },
  {
    "slug": "buddy",
    "name": "Buddy",
    "group": "Cockatoo",
    "photo": "/birds/buddy.jpg",
    "species": "Umbrella Cockatoo",
    "age": "25+ years",
    "sex": "Male (assumed)",
    "facts": "Cockatoo",
    "noise": 5,
    "exp": "Experienced homes only",
    "bio": "Meet Buddy.\n\nBuddy is a 25+ year old assumed male Umbrella Cockatoo.\n\nBuddy is incredibly sweet, and he just wants all the love you can give him!\n\nHe will charm you with his baby talk and make you laugh with his goofy antics.\n\nSend in your complete questionnaire and come meet Buddy soon!"
  },
  {
    "slug": "hita",
    "name": "Hita",
    "group": "Cockatoo",
    "photo": "/birds/hita.jpg",
    "species": "Umbrella Cockatoo",
    "age": "30+ years",
    "sex": "Female",
    "facts": "Cockatoo",
    "noise": 5,
    "exp": "Experienced homes only",
    "special": "No homes with male cockatoos (egg-laying history)",
    "bio": "Meet Hita.\n\nHita is a 30+ year old egg laying female Umbrella Cockatoo.\n\nHita is incredibly sweet and she is content to spend the day cuddling, playing, and exploring.\n\nHita will be an AMAZING companion for someone with large bird experience and the ability to spend a lot of quality time with her.\n\n*Due to Hita having a history of egg laying, she will NOT be adopted into a home with male Cockatoos.*"
  },
  {
    "slug": "charlie",
    "name": "Charlie",
    "group": "Cockatoo",
    "photo": "/birds/charlie.jpg",
    "species": "Goffin's Cockatoo",
    "age": "~40 years",
    "sex": "Male (assumed)",
    "facts": "Cockatoo",
    "noise": 5,
    "exp": "Experienced homes only",
    "special": "No dogs · prefers to be your only \"man\"",
    "bio": "Meet Charlie.\n\nCharlie is an approximately 40 year old assumed male Goffin's Cockatoo.\n\nCharlie LOVES to be the center of attention and will demand it to be so.\n\nCharlie definitely prefers women over men and he seems to do best being the only \"man\" in someone's life.\n\nCharlie has not had much experience around young children.\n\nCharlie would likely not do well in a home with dogs as he has attacked dogs in the past.\n\nCharlie is a cuddle bird and will take all the scritches you can offer.\n\nCharlie will make a great companion for someone who is willing to devote a LOT of time to him and work with him to overcome his extreme need to be the center of attention."
  },
  {
    "slug": "sunshine",
    "name": "Sunshine",
    "group": "Conure",
    "photo": "/birds/sunshine.jpg",
    "species": "Sun Conure",
    "age": "5+ years",
    "sex": "Female (assumed)",
    "facts": "Conure",
    "noise": 5,
    "exp": "Some experience",
    "bio": "Meet Sunshine.\n\nSunshine is a 5+ year old assumed female Sun Conure.\n\nWe don't have much information about Sunshine, and so far, she isn't very trusting with most humans.\n\nSunshine will need someone willing to go slow and be patient with her. She is not quick to open up and allow much interaction.\n\nShe does show great potential, and the right person for her will find an amazing companion in Sunshine!"
  },
  {
    "slug": "rio",
    "name": "Rio",
    "group": "Conure",
    "photo": "/birds/rio.jpg",
    "species": "Green-Cheek Conure",
    "age": "8 years",
    "sex": "Female",
    "facts": "Conure",
    "noise": 2,
    "exp": "Beginner-friendly",
    "bio": "Meet Rio.\n\nRio is an 8-year-old female Green Cheek Conure.\n\nRio has been cage-bound for the last several years and as a result, she's a little timid and doesn't really know \"what to do\" when she's out of her cage. She's learning though and she definitely is loving the freedom.\n\nRio is a little cuddlebug! She happily cuddles up for scritches and will contentedly allow pin feather help!\n\nRio is going to make an amazing companion for someone!"
  },
  {
    "slug": "isaac",
    "name": "Isaac",
    "group": "Conure",
    "photo": "/birds/isaac.jpg",
    "species": "Green-Cheek Conure",
    "age": "9 years",
    "sex": "Male (assumed)",
    "facts": "Conure",
    "noise": 2,
    "exp": "Beginner-friendly",
    "bio": "Isaac is a 9 year old green cheek conure. While we do not know his gender, his previous owner believed he is a male.\n\nIsaac is stubborn to come out of his cage, and once he's out he can be hard to catch. However, he does step up very easily if you approach him slowly.\n\nHe enjoys sitting on shoulders, but his favorite spot is to perch on top of your head and preen your hair. He will nuzzle into necks once comfortable and preen earlobes. He isn't fond of scratches, yet, but has warmed up to some of us here.\n\nCareful--he might even add a few of his own finishing touches to your clothes!"
  },
  {
    "slug": "ollie",
    "name": "Ollie",
    "group": "Conure",
    "photo": "/birds/ollie.jpg",
    "species": "Green-Cheek Conure",
    "age": "3 years",
    "sex": "Male",
    "facts": "Conure",
    "noise": 2,
    "exp": "Beginner-friendly",
    "bio": "Meet Ollie.\n\nOllie is a 3-year-old male Green Cheek Conure.\n\nOllie is a total sweetheart when he wants to be, but like all GCCs, Ollie has a mischievous side.\n\nOllie really wants to be a part of your every day activities and cuddle up for scritches and have great snacks and just live the life of luxury that a Green Cheek is meant to live!\n\nOllie is going to be a WONDERFUL addition to your flock!"
  },
  {
    "slug": "morgan",
    "name": "Morgan",
    "group": "Macaw",
    "photo": "/birds/morgan.jpg",
    "species": "Blue & Gold Macaw",
    "age": "~35 years",
    "sex": "Male",
    "facts": "Macaw",
    "noise": 5,
    "exp": "Experienced homes only",
    "bio": "Hi, I'm Morgan!\n\nI'm an approximately 35 year old male, Blue and Gold Macaw.\n\nLike most of my kind, I can be a little stand-offish when you first meet me. I'll tell you what, though, once I've deemed you worthy of my sweet side, I'll show you a darn good time!\n\nSome of my favorite pastime activities include: dancing (especially to Lil Wayne 😉), eating (bring on the fresh veggies!), and barking and biting my own leg when I'm trying to intimidate humans.\n\nI'm ready for you to come meet me, and maybe , just maybe, you'll be the human that I've been waiting for!"
  },
  {
    "slug": "koda",
    "name": "Koda",
    "group": "Macaw",
    "photo": "/birds/koda.jpg",
    "species": "Harlequin Macaw",
    "age": "60+ years",
    "sex": "Male (assumed)",
    "facts": "Macaw",
    "noise": 4,
    "exp": "Experienced homes only",
    "bio": "Hi, I'm Koda!\n\nI am a 60+ year old assumed male Harlequin Macaw.\n\nI take great pride in the fact that I have an amazing physique, and I make sure I'm always looking my best. A gentleman must always look his best. Showers are my FAVORITE thing in the world.\n\nLook, I'm an old man, and as such, I sometimes can be a little grumpy. I'll act like a feral dinosaur to keep you out of my face when I'm feeling testy.  I'm not too quick to warm up to some humans, but once I do, you'll find I'm actually really sweet, and I just want love. Who doesn't?!?\n\nLet's meet and see where things go! 😉"
  },
  {
    "slug": "indigo-birdie",
    "name": "Indigo Birdie",
    "group": "Macaw",
    "photo": "/birds/indigo-birdie.jpg",
    "species": "Blue & Gold Macaw",
    "age": "22 years",
    "sex": "Male (assumed)",
    "facts": "Macaw",
    "noise": 5,
    "exp": "Experienced homes only",
    "special": "Walks with a limp (born with deformed feet) — a total trooper",
    "bio": "Meet Indigo Birdie.\n\nIndigo Birdie is a 22 year old assumed male Blue and Gold Macaw.\n\nIndigo Birdie was born with deformed feet and slightly splayed legs. He has adjusted well to it in his life, and even though he walks with a limp and it's takes him a little bit longer to maneuver around, he still does great and it doesn't seem to cause him any pain. He's a trooper!\n\nIndigo Birdie is quite funny, and he'll keep you entertained with his antics and his bells that he loves to play.\n\nIf hearing a deranged rooster screaming for peanut butter toast is your thing, Indigo Birdie is the guy for you! 🤣\n\nYou've got to meet this guy! But be warned, you might fall in love with him!!"
  },
  {
    "slug": "marco",
    "name": "Marco",
    "group": "Macaw",
    "photo": "/birds/marco.jpg",
    "species": "Blue & Gold Macaw",
    "age": "~30 years",
    "sex": "Male (assumed)",
    "facts": "Macaw",
    "noise": 5,
    "exp": "Experienced homes only",
    "bio": "Hi! I'm Marco.\n\nI'm an approximately 30 year old assumed male Blue and Gold Macaw.\n\nI hate this part of these profiles. It's so hard to talk about yourself, ya know?\n\nWhat can I say?\n\nWell, some would say I'm a \"rebel bird.\" I dont make the best choices sometimes, and occasionally, someone has \"allegedly\" gotten bit. It's not that I WANT to hurt anyone, I just get overwhelmed with excitement sometimes or overstimulated, and I have \"allegedly\" bitten someone before. If you want to be a part of my flock, you're going to have to be patient with me and be willing to learn my body language. If you can help me work through situations in positive ways before I get carried away, that would be great! Oh, and someone who wants to dance and laugh with me would be even better! I LOVE a good joke, and if you're laughing, I want to be, too!\n\nI've been told I'm quite goofy and hilarious. Yes, I have made a bad rep for himself on occasion, but if you slow down with me, give me a chance to look you over and assess you, you'll be met by a curious and charming lover bird. It takes me a bit to warm up, but once I do, I'm yours forever! I like to mess with new people sometimes. I really am funny.\n\nI will need someone with patience, the willingness to learn my body language, and to work with me to express myself in more positive ways.\n\nExperience with macaws would be a huge bonus."
  },
  {
    "slug": "jessie",
    "name": "Jessie",
    "group": "Macaw",
    "photo": "/birds/jessie.jpg",
    "species": "Blue & Gold Macaw",
    "age": "30+ years",
    "sex": "Male (assumed)",
    "facts": "Macaw",
    "noise": 4,
    "exp": "Experienced homes only",
    "special": "No in-shell walnuts (seizure history)",
    "bio": "Meet Jessie.\n\nJessie is a 30+ year old assumed male Blue and Gold Macaw.\n\nJessie is also starting to open up a bit and show us some of his personality. He has been quite timid so far.\n\nBeing here in the Sanctuary can be a scary experience, and Jessie is a careful observer, just taking it all in right now. We have a feeling he's quite goofy, though, based on the times he's been \"caught\" being cheeky.\n\nIt should be noted that Jessie has been reported to have had seizures after consuming walnuts in the shell. Walnuts out of the shell and all other nuts have seemed to be of no issue.\n\nJessie will need a human with patience, an understanding of macaws, and the ability to provide structure, love, proper nutrition, and enrichment."
  },
  {
    "slug": "savannah",
    "name": "Savannah",
    "group": "Macaw",
    "photo": "/birds/savannah.jpg",
    "species": "Catalina Macaw (hybrid)",
    "age": "21 years",
    "sex": "Female (assumed)",
    "facts": "Macaw",
    "noise": 4,
    "exp": "Experienced homes only",
    "special": "Harness-trained adventurer",
    "bio": "Meet Savannah.\n\nSavannah is a 21 year old assumed female macaw.\n\nReportedly, Savannah is a Catalina Macaw. However, we aren't 100% convinced. Possibly a miligold or different hybrid?\n\nEither way, Savannah is for sure going to be someone's best friend for life! This sweet girl likes the majority of people, willingly steps up and hangs out with you and she will take all the scritches you have to offer.\n\nSavannah is harness trained and she would love to go out and about and explore the world with you!"
  },
  {
    "slug": "benji",
    "name": "Benji",
    "group": "Macaw",
    "photo": "/birds/benji.jpg",
    "species": "Blue & Gold Macaw",
    "age": "~34 years",
    "sex": "Male (assumed)",
    "facts": "Macaw",
    "noise": 5,
    "exp": "Experienced homes only",
    "bio": "Meet Benji.\n\nBenji is an approximately 34 year old assumed male Blue and Gold Macaw.\n\nBenji's owner recently passed away, and Benji is in need of a new human to love.\n\nBenji seems to have preferred his mom over anyone else and was known to spend his evenings cuddled up with her. He doesn't trust new people easily and will stand his ground when he's unsure of someone.\n\nBenji is a goofy, playful, funny bird and LOVES to show off his beautiful wings. Someone who is willing to work on gaining his trust will find an amazing companion in him!"
  },
  {
    "slug": "skittles",
    "name": "Skittles",
    "group": "Macaw",
    "photo": "/birds/skittles.jpg",
    "species": "Blue & Gold Macaw",
    "age": "8 years",
    "sex": "Male (assumed)",
    "facts": "Macaw",
    "noise": 4,
    "exp": "Experienced homes only",
    "special": "Fully flighted — recall training encouraged",
    "bio": "Meet Skittles.\n\nSkittles is an 8 year old assumed male Blue and Gold Macaw.\n\nSkittles is a little bit shy at first but once he's comfortable with you he allows you to give him some scritches. He is willing to step up for those he's comfortable with.\n\nSkittles is a goofy, playful, young Macaw. As such, he can get a little loud sometimes but it's very quick bursts of loudness and then he's back to just silly.\n\nSkittles will need someone with large bird experience as he's still young and needs experienced training.\n\nSkittles is fully flighted and he's pretty good at it so recall and harness training are going to be highly encouraged."
  },
  {
    "slug": "max",
    "name": "Max",
    "group": "Macaw",
    "photo": "/birds/max.jpg",
    "species": "Blue & Gold Macaw",
    "age": "40 years",
    "sex": "Male",
    "facts": "Macaw",
    "noise": 5,
    "exp": "Experienced homes only",
    "bio": "Meet Max.\n\nMax is a 40-year-old male Blue and Gold Macaw.\n\nMax is a little nervous around new people but once he is familiar and comfortable with someone, he's a pretty cool bird!\n\nMax loves to eat, hang out on his cage and dance, and get all the loving scritches you can offer.\n\nMax will make a great companion for someone with large bird experience."
  },
  {
    "slug": "maui",
    "name": "Maui",
    "group": "Macaw",
    "photo": "/birds/maui.jpg",
    "species": "Blue & Gold Macaw",
    "age": "17 years",
    "sex": "Male (assumed)",
    "facts": "Macaw",
    "noise": 5,
    "exp": "Experienced homes only",
    "special": "Fully flighted — recall training encouraged",
    "bio": "Looking for one of the most entertaining companions that you could ever ask for?\n\nWell, look no further!\n\nMeet Maui.\n\nMaui is a 17-year-old assumed male Blue and Gold Macaw.\n\nMaui is a fully flighted Macaw and he will take flight with no qualms about it.\n\nWhile Maui is very adorable and entertaining, he is still a Macaw and macaws have big needs.\n\nMaui will need a human with patience, a willingness to train him on recall for his safety, and an understanding of the nutritional, emotional, and physical needs of a macaw.\n\nHarness training would be great for Maui."
  },
  {
    "slug": "sinbad",
    "name": "Sinbad",
    "group": "Macaw",
    "photo": "/birds/sinbad.jpg",
    "species": "Harlequin Macaw",
    "age": "~35 years",
    "sex": "Male",
    "facts": "Macaw",
    "noise": 4,
    "exp": "Experienced homes only",
    "bio": "Meet Sinbad.\n\nSinbad is an approximately 35-year-old male Harlequin Macaw.\n\nSinbad is just learning how to be a Macaw and he is finding his voice and playful side.\n\nSinbad has shown no aggression but has a timid and nervous side to him. He prefers to avoid rather than react.\n\nSinbad will need a human with patience and understanding and experience with Macaws. Based on everything he's shown us so far, Sinbad has the capability to be an amazing companion for the right human!"
  },
  {
    "slug": "boyd-floyd",
    "name": "Boyd & Floyd",
    "group": "Parakeet",
    "photo": "/birds/boyd-floyd.jpg",
    "species": "Budgies",
    "age": "4 years",
    "sex": "Bonded pair",
    "facts": "Parakeet",
    "noise": 1,
    "exp": "Beginner-friendly",
    "bonded": true,
    "bio": "Meet Boyd & Floyd.\n\nBoyd & Floyd are 4-year-old bonded Budgies.\n\nBoyd & Floyd are not hand-tame.\n\nThey are very active, chirpy, happy little Budgies."
  },
  {
    "slug": "teegan-mango",
    "name": "Teegan & Mango",
    "group": "Parakeet",
    "photo": "/birds/teegan-mango.jpg",
    "species": "Budgies",
    "age": "5+ years",
    "sex": "Bonded pair",
    "facts": "Parakeet",
    "noise": 1,
    "exp": "Beginner-friendly",
    "bonded": true,
    "bio": "Meet Teegan & Mango.\n\nTeegan & Mango are 5+ year-old bonded Budgies.\n\nTeegan & Mango are not hand-tame.\n\nThey are very active, chirpy, happy little Budgies."
  },
  {
    "slug": "oatmeal",
    "name": "Oatmeal",
    "group": "Other",
    "photo": "/birds/oatmeal.jpg",
    "species": "Indian Ringneck Parakeet",
    "age": "13 years",
    "sex": "Male",
    "facts": "Ringneck",
    "noise": 4,
    "exp": "Experienced homes only",
    "special": "No cats or dogs (fall risk) · seizure history",
    "bio": "Oatmeal is a 13 year old male Indian Ringneck parakeet.\n\nHe was born on June 17, 2011.\n\nOatmeal was previously kept in a college student's closet due to his volume. He was rescued twice afterwards, and eventually rehabilitated enough to where he transformed from being a plucked, malnourished bird into a friendly, outgoing guy.\n\nOatmeal does have some quirks - he is an anxious bird and until recently, he was reliant on Cookie, his counterpart. Cookie has recently passed away and Oatmeal is adjusting to that loss.\n\nOatmeal has a history of seizures and was a severe plucker to the point of mutilation. He needs an owner who is home often, has many hours to devote to training and rehabilitation, and who will accept him with his quirks.\n\n**Because of Oatmeal's history of seizures, we are asking that he go to a home with remarkable parrot ownership experience.\n\n**Because of Oatmeal being unable to fly, being a fall risk, and roaming on the ground most of the time, we ask he does not go to a home with cats or dogs."
  },
  {
    "slug": "city",
    "name": "City",
    "group": "Other",
    "photo": "/birds/city.jpg",
    "species": "Senegal Parrot",
    "age": "~10 years",
    "sex": "Male",
    "facts": "Senegal",
    "noise": 3,
    "exp": "Experienced homes only",
    "bio": "Meet City!\n\nCity is an approximately 10 year old male Senegal parrot.\n\nCity does show some cage aggression, which is common with the Senegal species. City has a history of biting \"for no reason\" and his bite can be pretty bad. At the same time, he is a total cuddle bug and loves to be scritched on his cheeks and all over his head. City will need someone with patience, an ability to learn his body language, the ability to take some bad bites and work through them, and someone willing to put some hard work into positively training the biting out of him.\n\nHe loves nuts, specifically almonds and cashews.\n\nHe is a very animated boy who loves to mimic and makes several noises such as a dog barking, various whistles, spaceship noises, and more. He is a little chatterbox when he's comfortable and happy."
  },
  {
    "slug": "kiko",
    "name": "Kiko",
    "group": "Other",
    "photo": "/birds/kiko.jpg",
    "species": "Quaker Parrot",
    "age": "4 years",
    "sex": "Female (assumed)",
    "facts": "Quaker",
    "noise": 3,
    "exp": "Some experience",
    "special": "Quakers require WI state registration",
    "bio": "Meet Kiko.\n\nKiko is a 4 year old assumed female Quaker.\n\nKiko, like most Quakers, can be a bit cage aggressive, but once out, Kiko will hang out on your arm or shoulder and share a delicious apple if you let her!\n\nKiko can be an incredibly sweet bird, but she can also be a little stinker. Kiko LOVES spray baths, apples, and millet.\n\nKiko seems to favor women over men.\n\nKiko has not been raised around children, and her bite suggests it'd be best if she wasn't.\n\nKiko will need to be registered with the state when you adopt her.\n\nSee: https:\\/\\/docs.legis.wisconsin.gov\\/...\\/adm...\\/nr\\/001\\/40\\/04\\/3\\/h"
  },
  {
    "slug": "melody-lyric",
    "name": "Melody & Lyric",
    "group": "Other",
    "photo": "/birds/melody-lyric.jpg",
    "species": "Fischer's Lovebirds",
    "age": "3 & 5 years",
    "sex": "Bonded pair",
    "facts": "Lovebird",
    "noise": 2,
    "exp": "Some experience",
    "bonded": true,
    "bio": "Meet Melody and Lyric.\n\nMelody and Lyric are Fischer's Lovebirds. Melody(Yellow\\/brown) is almost 3 years old and Lyric(White\\/blue) is approximately 5 years old.\n\nMelody and Lyric are bonded and as you can see, Lyric relies heavily on Melody to be the brave one!\n\nMelody and Lyric need someone with patience who is willing to work on getting them hand tame and some recall training is definitely in order for them."
  },
  {
    "slug": "gizmo",
    "name": "Gizmo",
    "group": "Other",
    "photo": "/birds/gizmo.jpg",
    "species": "Senegal Parrot",
    "age": "15 years",
    "sex": "Female (assumed)",
    "facts": "Senegal",
    "noise": 3,
    "exp": "Some experience",
    "special": "No dogs · old wing injury, flies a little",
    "bio": "Have you ever considered opening your heart up to a sweet little Senegal?\n\nOf course you haven't, because Senegals aren't sweet! They are vicious, bitey, sneak attack jerks- ESPECIALLY if named Gizmo..... I mean, Hello! Gremlins!!  Am I right?!?\n\n😆 Just kidding, Meet Gizmo.\n\nGizmo is a 15-year-old assumed female Senegal.\n\nGizmo DOES have a mean streak with dogs and she definitely needs a home without them.\n\nHowever, aside from that, Gizmo is a sweet girl and she loves to hang out with you and get all the scritches you can offer.\n\nShe is very nervous of new people at first and she isn't the greatest at responding to \"step up\" or other basic \"desired bird commands\".  She is learning though!\n\nGizmo has a previous wing injury that has left her wing slightly out of place but she doesn't appear to be in pain. She doesn't have full mobility in it and flying is difficult for her but not impossible.\n\nGizmo will make an excellent companion for someone with extra love and patience and no desire to have a dog."
  }
];
