/* ============================================================
   SPECIES KNOWLEDGE + ORG FACTS
   Species numbers (lifespan, cost, decibels) power the
   planning interactives and Companion Facts labels.
   Org info, policies, and form links are the real ones from
   feathered-friends.com.
   ============================================================ */

export const SPECIES = {
  Macaw: {
    plumage: ['#2456a8', '#e8a33d', '#c43a2a'],
    lifespan: [50, 80],
    lifespanLabel: '50–80 years',
    monthlyCost: [125, 250],
    decibels: 106,
    dbCompare: 'a jackhammer at ten feet',
    daily: '4+ hours of company, every day',
    mess: 4,
    voice: 'Can be heard from the street. Really.',
    inMath: true,
  },
  Cockatoo: {
    plumage: ['#f4f1e6', '#f2d46a', '#e8a33d'],
    lifespan: [40, 70],
    lifespanLabel: '40–70 years',
    monthlyCost: [110, 220],
    decibels: 120,
    dbCompare: 'a rock concert, front row',
    daily: '4+ hours of company — they will insist',
    mess: 5,
    voice: 'Among the loudest animals kept as pets. We mean it.',
    inMath: true,
  },
  'African Grey': {
    plumage: ['#8e9296', '#c6cbce', '#c0432b'],
    lifespan: [40, 60],
    lifespanLabel: '40–60 years',
    monthlyCost: [100, 200],
    decibels: 70,
    dbCompare: 'a very opinionated dinner guest',
    daily: '3–4 hours of company',
    mess: 3,
    voice: 'Moderate volume — but a world-class mimic of everything you say.',
    inMath: true,
  },
  Amazon: {
    plumage: ['#3e8e4b', '#b7d34a', '#e8a33d'],
    lifespan: [40, 70],
    lifespanLabel: '40–70 years',
    monthlyCost: [100, 200],
    decibels: 96,
    dbCompare: 'a lawnmower in your kitchen',
    daily: '3–4 hours of company',
    mess: 3,
    voice: 'Opera hour at dawn and dusk, every day.',
    inMath: true,
  },
  Conure: {
    plumage: ['#3e8e4b', '#e8a33d', '#c0432b'],
    lifespan: [20, 30],
    lifespanLabel: '20–30 years',
    monthlyCost: [75, 150],
    decibels: 102,
    dbCompare: 'a smoke alarm that loves you',
    daily: '3–4 hours of company',
    mess: 3,
    voice: 'A very big voice in a very small body.',
    inMath: true,
  },
  Cockatiel: {
    plumage: ['#b9bdbf', '#f2e27a', '#f0a24a'],
    lifespan: [15, 25],
    lifespanLabel: '15–25 years',
    monthlyCost: [50, 100],
    decibels: 65,
    dbCompare: 'a cheerful teakettle',
    daily: '2–3 hours of company',
    mess: 2,
    voice: 'Gentle whistles and contact calls.',
    inMath: true,
  },
  Parakeet: {
    plumage: ['#4bae5a', '#5ac8e0', '#f2e27a'],
    lifespan: [10, 15],
    lifespanLabel: '10–15 years',
    monthlyCost: [40, 80],
    decibels: 68,
    dbCompare: 'a chatty little radio',
    daily: '2–3 hours of company',
    mess: 2,
    voice: 'Cheerful all-day chatter.',
    inMath: true,
  },
  Ringneck: {
    plumage: ['#4bae5a', '#5ac8e0', '#e05a3a'],
    lifespan: [25, 30],
    lifespanLabel: '25–30 years',
    monthlyCost: [60, 120],
    decibels: 95,
    dbCompare: 'a whistling kettle with opinions',
    daily: '2–3 hours of company',
    mess: 3,
    voice: 'Talkative, with a piercing flock call.',
    inMath: false,
  },
  Senegal: {
    plumage: ['#3e8e4b', '#e8a33d', '#5b6770'],
    lifespan: [25, 40],
    lifespanLabel: '25–40 years',
    monthlyCost: [60, 120],
    decibels: 75,
    dbCompare: 'a polite chatterbox',
    daily: '2–3 hours of company',
    mess: 2,
    voice: 'One of the quieter parrots — with chatterbox moments.',
    inMath: false,
  },
  Quaker: {
    plumage: ['#4bae5a', '#b9bdbf', '#5ac8e0'],
    lifespan: [20, 30],
    lifespanLabel: '20–30 years',
    monthlyCost: [50, 100],
    decibels: 93,
    dbCompare: 'a tiny town crier',
    daily: '2–3 hours of company',
    mess: 3,
    voice: 'Busy, chatty, and a gifted little talker.',
    inMath: false,
  },
  Lovebird: {
    plumage: ['#f2c14e', '#e05a3a', '#4bae5a'],
    lifespan: [10, 15],
    lifespanLabel: '10–15 years',
    monthlyCost: [40, 80],
    decibels: 83,
    dbCompare: 'a squeaky-toy chorus',
    daily: '2 hours of company (more if single)',
    mess: 2,
    voice: 'High cheerful chirps, most of the day.',
    inMath: false,
  },
};

export const speciesFacts = (group) => SPECIES[group] || SPECIES.Conure;

/* Real adopted birds from the sanctuary's success-stories page */
export const HAPPY_LANDINGS = [
  'Johnny & June',
  'OB',
  'Inga',
  'Ruby',
  'Grace & Frankie',
  'Larry Bird',
  'Misty',
  'Cheeto',
  'Fiona',
  'Chilly',
  'Vincent',
  'Pip Squeak',
  'Penny & Charlie',
  'Louie',
  'Walter & Skye',
  'Packer',
  'Cranberry',
  'Akio',
];

export const ORG = {
  name: 'Feathered Friends Sanctuary & Rescue, Inc.',
  short: 'Feathered Friends',
  est: 2000,
  address: '1570 County Road A, Edgerton, WI 53534',
  email: 'info@feathered-friends.com',
  phone: '608-302-1732',
  phoneNote: 'voicemail only — we return calls between feedings',
  donateUrl: 'https://www.paypal.com/donate/?hosted_button_id=Y5DW68FD7QJVS',
  facebook: 'https://www.facebook.com/FeatheredFriendsWI',
  site: 'https://www.feathered-friends.com',
  notice: 'Open by appointment only — email us to schedule a visit',
  radiusNote: 'Adoptions are limited to homes within a two-hour drive of Edgerton, WI — the visits matter that much.',
  forms: {
    adoption:
      'https://docs.google.com/forms/d/e/1FAIpQLSfZdMz6i1gzeJaQDzB5pyejwxNjkW3T9p465aEYKQE5VZoBkQ/viewform',
    surrender:
      'https://docs.google.com/forms/d/e/1FAIpQLSdd1WCpXHwQ9P8BfP578qyP0uQgj3F1LeOqy6Dbxw7dnnmCYA/viewform',
    boarding:
      'https://docs.google.com/forms/d/e/1FAIpQLScEDELU4xsTI4Qg_yKtyB3gsS2eO5hsTac7PbPGzTYo7rQySw/viewform',
    volunteer:
      'https://docs.google.com/forms/d/e/1FAIpQLScjfnq1ClBtcXeBjRubWcktS2Y93sV6okhMgras33WLj7w_aA/viewform',
  },
};
