/* ============================================================
   THE FLOCK — species knowledge + resident birds.
   Species numbers (lifespan, cost, decibels) power the honesty
   interactives. Sources: typical companion-parrot care ranges.
   Bird listings are sample data for this concept build.
   ============================================================ */

export const SPECIES = {
  Macaw: {
    plumage: ['#2456a8', '#e8a33d', '#c43a2a'],
    lifespan: [50, 80],
    lifespanLabel: '50–80 years',
    monthlyCost: [125, 250],
    decibels: 106,
    dbCompare: 'a jackhammer at ten feet',
    daily: '4+ hours of company, every day',
    mess: 4,
    voice: 'Can be heard from the street. Really.',
  },
  Cockatoo: {
    plumage: ['#f4f1e6', '#f2d46a', '#e8a33d'],
    lifespan: [40, 70],
    lifespanLabel: '40–70 years',
    monthlyCost: [110, 220],
    decibels: 120,
    dbCompare: 'a rock concert, front row',
    daily: '4+ hours of company — they will insist',
    mess: 5,
    voice: 'Among the loudest animals kept as pets. We mean it.',
  },
  'African Grey': {
    plumage: ['#8e9296', '#c6cbce', '#c0432b'],
    lifespan: [40, 60],
    lifespanLabel: '40–60 years',
    monthlyCost: [100, 200],
    decibels: 70,
    dbCompare: 'a very opinionated dinner guest',
    daily: '3–4 hours of company',
    mess: 3,
    voice: 'Moderate volume — but a world-class mimic of everything you say.',
  },
  Amazon: {
    plumage: ['#3e8e4b', '#b7d34a', '#e8a33d'],
    lifespan: [40, 70],
    lifespanLabel: '40–70 years',
    monthlyCost: [100, 200],
    decibels: 96,
    dbCompare: 'a lawnmower in your kitchen',
    daily: '3–4 hours of company',
    mess: 3,
    voice: 'Opera hour at dawn and dusk, every day.',
  },
  Conure: {
    plumage: ['#3e8e4b', '#e8a33d', '#c0432b'],
    lifespan: [20, 30],
    lifespanLabel: '20–30 years',
    monthlyCost: [75, 150],
    decibels: 102,
    dbCompare: 'a smoke alarm that loves you',
    daily: '3–4 hours of company',
    mess: 3,
    voice: 'A very big voice in a very small body.',
  },
  Cockatiel: {
    plumage: ['#b9bdbf', '#f2e27a', '#f0a24a'],
    lifespan: [15, 25],
    lifespanLabel: '15–25 years',
    monthlyCost: [50, 100],
    decibels: 65,
    dbCompare: 'a cheerful teakettle',
    daily: '2–3 hours of company',
    mess: 2,
    voice: 'Gentle whistles and contact calls.',
  },
  Parakeet: {
    plumage: ['#4bae5a', '#5ac8e0', '#f2e27a'],
    lifespan: [10, 15],
    lifespanLabel: '10–15 years',
    monthlyCost: [40, 80],
    decibels: 68,
    dbCompare: 'a chatty little radio',
    daily: '2–3 hours of company',
    mess: 2,
    voice: 'Cheerful all-day chatter.',
  },
};

export const speciesFacts = (group) => SPECIES[group] || SPECIES.Conure;

export const BIRDS = [
  {
    id: 'packer',
    name: 'Packer',
    species: 'Blue & Gold Macaw',
    group: 'Macaw',
    age: 'Adult',
    sex: 'Male',
    status: 'available',
    noise: 5,
    experience: 'Experienced homes only',
    goodWith: 'Adults-only or bird-savvy households',
    monthsWaiting: 7,
    bio: 'Packer is a big personality in a big blue-and-gold package. He loves fresh chop, wood blocks he can demolish, and announcing dinnertime to the whole building. He is looking for an experienced home that understands macaw volume, macaw beaks, and macaw hearts.',
  },
  {
    id: 'elsa-olaf',
    name: 'Elsa & Olaf',
    species: 'Cockatiels · bonded pair',
    group: 'Cockatiel',
    age: 'Young adults',
    sex: 'Pair',
    status: 'available',
    noise: 2,
    experience: 'Beginner-friendly',
    goodWith: 'First-time bird families',
    monthsWaiting: 4,
    bonded: true,
    bio: 'Elsa and Olaf are a devoted bonded pair who must be adopted together. They whistle duets in the morning, nap on the same perch, and make cockatiel ownership look easy — because together, they mostly are.',
  },
  {
    id: 'gizmo',
    name: 'Gizmo',
    species: 'Yellow-Naped Amazon',
    group: 'Amazon',
    age: 'Senior',
    sex: 'Male',
    status: 'available',
    noise: 4,
    experience: 'Some experience',
    goodWith: 'Patient adults, routine-loving homes',
    monthsWaiting: 11,
    bio: 'Gizmo is a distinguished older gentleman with an impressive vocabulary and strong opinions about breakfast. Senior parrots like Gizmo are the best-kept secret in rescue: settled, communicative, and deeply grateful for a routine.',
  },
  {
    id: 'morgan',
    name: 'Morgan',
    species: 'Green-Cheek Conure',
    group: 'Conure',
    age: 'Adult',
    sex: 'Female',
    status: 'available',
    noise: 2,
    experience: 'Some experience',
    goodWith: 'Attentive adults',
    monthsWaiting: 14,
    bio: 'Morgan is a pocket-sized clown who wants to be involved in everything you do. Green cheeks are quieter than most conures, but Morgan still needs several hours of out-of-cage time and a human who laughs at her jokes.',
  },
  {
    id: 'cleo',
    name: 'Cleo',
    species: 'Umbrella Cockatoo',
    group: 'Cockatoo',
    age: 'Adult',
    sex: 'Female',
    status: 'sanctuary',
    noise: 5,
    experience: 'Sanctuary resident',
    goodWith: 'Sponsors — she keeps our volunteers humble',
    monthsWaiting: 0,
    bio: 'Cleo is one of our permanent sanctuary residents — she will live out her whole long life here, loved and loud. You can be part of that life by sponsoring her care.',
  },
  {
    id: 'juno',
    name: 'Juno',
    species: 'Congo African Grey',
    group: 'African Grey',
    age: 'Adult',
    sex: 'Female',
    status: 'available',
    noise: 3,
    experience: 'Experienced homes only',
    goodWith: 'Calm households that talk to her like a person',
    monthsWaiting: 9,
    bio: 'Juno knows forty-one words and uses them with intent. She asks the room "you okay?" when someone sneezes. Greys bond deeply and think constantly — Juno needs a home that treats her mind as seriously as her wings.',
  },
];

export const HAPPY_LANDINGS = [
  { name: 'Sunny', species: 'Sun Conure', town: 'Madison' },
  { name: 'Pistachio', species: 'Cockatiel', town: 'Janesville' },
  { name: 'Kiwi', species: 'Parakeet', town: 'Fort Atkinson' },
  { name: 'Rio', species: 'Amazon', town: 'Milwaukee' },
  { name: 'Baby', species: 'Cockatoo', town: 'Stoughton' },
  { name: 'Merlin', species: 'African Grey', town: 'Verona' },
  { name: 'Peaches', species: 'Conure', town: 'Whitewater' },
  { name: 'Ziggy', species: 'Cockatiel', town: 'Oregon' },
];

export const ORG = {
  name: 'Feathered Friends Sanctuary & Rescue, Inc.',
  short: 'Feathered Friends',
  est: 2000,
  address: '1570 County Road A, Edgerton, WI 53534',
  email: 'info@feathered-friends.com',
  phone: '608-302-1732',
  phoneNote: 'voicemail only — we return calls between feedings',
  donateUrl: 'https://www.paypal.com/donate/?hosted_button_id=Y5DW68FD7QJVS',
  facebook: 'https://www.facebook.com/Feathered-Friends-Sanctuary-Rescue-171994686190287/',
  site: 'https://www.feathered-friends.com',
};
